version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccsds_api
    working_dir: /home/ccsds_source/ccsds_final_project/api/build
    command: ["/home/ccsds_source/ccsds_final_project/api/build/api"]
    restart: always
    ports:
      - "5000:5000"  # Adjust if needed
      - "6000:6000"
    networks:
      - ccsds_network
    depends_on:
      - ws
    environment:
      - MONGODB_URI=mongodb://192.168.102.79:27017
      - DEFAULT_STRUCTURE_FILE_PATH=/home/ccsds_source/ccsds_final_project/ws/build/uploads
    deploy:
      resources:
        limits:
          cpus: '6.0'
        reservations:
          cpus: '2.0'

  ws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccsds_ws
    working_dir: /home/ccsds_source/ccsds_final_project/ws/build
    # entrypoint: /bin/true
    # restart: always
    networks:
      - ccsds_network
    deploy:
      resources:
        limits:
          cpus: '6.0'
    cpus: '6.0'
    cpuset: "0-6"

networks:
  ccsds_network:
    driver: bridge
